spring.application.name=weibo
# 单个文件最大大小（默认 1MB）
spring.servlet.multipart.max-file-size=50MB
# 整个请求（包含所有文件和表单数据）的最大大小（默认 10MB）
spring.servlet.multipart.max-request-size=100MB

#server.port=8000 端口
#server.servlet.context-path=/xw 前缀

# 禁用静态资源映射，避免接口路径被当作静态资源
spring.web.resources.add-mappings=false

# ===============================
# MyBatis-Plus 配置
# ===============================
# Mapper XML 文件路径
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
# 实体类扫描包
mybatis-plus.type-aliases-package=com.hn.it.weibo.entity
# 开启驼峰命名转换
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 日志配置（开发环境开启 SQL 日志）
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ===============================
# 数据库连接配置
# ===============================

# 1. 数据库驱动（MySQL 8.x 固定写法）
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. 数据库连接 URL
# 格式：jdbc:mysql://主机:端口/数据库名?参数
# 这里的 weibo 对应你 Navicat 左侧显示的数据库名
spring.datasource.url=jdbc:mysql://localhost:3306/xw?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai

# 3. 数据库用户名 8022
spring.datasource.username=root

# 4. 数据库密码（你提供的密码）
spring.datasource.password=12345678

# ===============================
# 邮件配置 (QQ 邮箱 SMTP)
# ===============================
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=1247079250@qq.com
spring.mail.password=ububplugnodvbbdc
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# 引用 Windows 环境变量
#my.aliyun.api-key=${MY_ALIYUN_APIKEY}
my.aliyun.api-key=sk-46a614aeb6e04c45bd76b201389e692d

# 图片上传存储目录（云服务器绝对路径）
file.upload.image-dir=/var/www/weibo-system/uploads
# 静态资源访问路径前缀
file.static.path-prefix=/imgs/
